Py3 does not have str.decode()
Skipping this shows no negative effect for me (but this must have been here for a reason).

<   475.5013> 00:11:07.4774 Traceback (most recent call last):
<   475.5014> 00:11:07.4775   File "/usr/lib/enigma2/python/Navigation.py", line 93, in dispatchEvent
<   475.5028> 00:11:07.4789     x(i)
<   475.5029> 00:11:07.4790   File "/usr/lib/enigma2/python/Components/ServiceEventTracker.py", line 85, in event
<   475.5039> 00:11:07.4800     func[2]()
<   475.5040> 00:11:07.4801   File "/usr/lib/enigma2/python/Plugins/Extensions/HbbTV/plugin.py", line 297, in _cb_ait_detected
<   475.5053> 00:11:07.4814     self._app_info = self.get_autostart_application()
<   475.5054> 00:11:07.4815   File "/usr/lib/enigma2/python/Plugins/Extensions/HbbTV/plugin.py", line 350, in get_autostart_application
<   475.5062> 00:11:07.4823     if reader.doOpen(info, self.aitReader):
<   475.5062> 00:11:07.4823   File "/usr/lib/enigma2/python/Plugins/Extensions/HbbTV/aitreader.py", line 86, in doOpen
<   475.5066> 00:11:07.4827     document = document.decode("cp1252").encode("utf-8")
<   475.5067> 00:11:07.4828 AttributeError: 'str' object has no attribute 'decode'